#ifndef _PYCGLES2_GL_EXT_GEOMETRY_SHADER_H_
#define _PYCGLES2_GL_EXT_GEOMETRY_SHADER_H_
#ifdef GL_EXT_geometry_shader
#include <Python.h>
#include <pycgles2.h>
#include "gl.h"
#include "util.h"
#include "ctxstruct.h"


/* TODO(NotImplemented): glFramebufferTextureEXT */
static PyObject *
PyCGLES2_glFramebufferTextureEXT(PyCGLES2_Context *self, PyObject *args, PyObject *kwds)
{
    /* void glFramebufferTextureEXT (GLenum target, GLenum attachment, GLuint texture, GLint level) */
    PyErr_SetString(PyExc_NotImplementedError, "glFramebufferTextureEXT");
    return NULL;
}


static int
PyCGLES2_GL_EXT_geometry_shader(PyObject *m)
{
    static const PyCGLES2_Enum enums[] = {
        {"GL_GEOMETRY_SHADER_EXT", GL_GEOMETRY_SHADER_EXT},
        {"GL_GEOMETRY_SHADER_BIT_EXT", GL_GEOMETRY_SHADER_BIT_EXT},
        {"GL_GEOMETRY_LINKED_VERTICES_OUT_EXT", GL_GEOMETRY_LINKED_VERTICES_OUT_EXT},
        {"GL_GEOMETRY_LINKED_INPUT_TYPE_EXT", GL_GEOMETRY_LINKED_INPUT_TYPE_EXT},
        {"GL_GEOMETRY_LINKED_OUTPUT_TYPE_EXT", GL_GEOMETRY_LINKED_OUTPUT_TYPE_EXT},
        {"GL_GEOMETRY_SHADER_INVOCATIONS_EXT", GL_GEOMETRY_SHADER_INVOCATIONS_EXT},
        {"GL_LAYER_PROVOKING_VERTEX_EXT", GL_LAYER_PROVOKING_VERTEX_EXT},
        {"GL_LINES_ADJACENCY_EXT", GL_LINES_ADJACENCY_EXT},
        {"GL_LINE_STRIP_ADJACENCY_EXT", GL_LINE_STRIP_ADJACENCY_EXT},
        {"GL_TRIANGLES_ADJACENCY_EXT", GL_TRIANGLES_ADJACENCY_EXT},
        {"GL_TRIANGLE_STRIP_ADJACENCY_EXT", GL_TRIANGLE_STRIP_ADJACENCY_EXT},
        {"GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT", GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT},
        {"GL_MAX_GEOMETRY_UNIFORM_BLOCKS_EXT", GL_MAX_GEOMETRY_UNIFORM_BLOCKS_EXT},
        {"GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_EXT", GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_EXT},
        {"GL_MAX_GEOMETRY_INPUT_COMPONENTS_EXT", GL_MAX_GEOMETRY_INPUT_COMPONENTS_EXT},
        {"GL_MAX_GEOMETRY_OUTPUT_COMPONENTS_EXT", GL_MAX_GEOMETRY_OUTPUT_COMPONENTS_EXT},
        {"GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT", GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT},
        {"GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT", GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT},
        {"GL_MAX_GEOMETRY_SHADER_INVOCATIONS_EXT", GL_MAX_GEOMETRY_SHADER_INVOCATIONS_EXT},
        {"GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT", GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT},
        {"GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_EXT", GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_EXT},
        {"GL_MAX_GEOMETRY_ATOMIC_COUNTERS_EXT", GL_MAX_GEOMETRY_ATOMIC_COUNTERS_EXT},
        {"GL_MAX_GEOMETRY_IMAGE_UNIFORMS_EXT", GL_MAX_GEOMETRY_IMAGE_UNIFORMS_EXT},
        {"GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_EXT", GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_EXT},
        {"GL_FIRST_VERTEX_CONVENTION_EXT", GL_FIRST_VERTEX_CONVENTION_EXT},
        {"GL_LAST_VERTEX_CONVENTION_EXT", GL_LAST_VERTEX_CONVENTION_EXT},
        {"GL_UNDEFINED_VERTEX_EXT", GL_UNDEFINED_VERTEX_EXT},
        {"GL_PRIMITIVES_GENERATED_EXT", GL_PRIMITIVES_GENERATED_EXT},
        {"GL_FRAMEBUFFER_DEFAULT_LAYERS_EXT", GL_FRAMEBUFFER_DEFAULT_LAYERS_EXT},
        {"GL_MAX_FRAMEBUFFER_LAYERS_EXT", GL_MAX_FRAMEBUFFER_LAYERS_EXT},
        {"GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT", GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT},
        {"GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT", GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT},
        {"GL_REFERENCED_BY_GEOMETRY_SHADER_EXT", GL_REFERENCED_BY_GEOMETRY_SHADER_EXT},
        {NULL, 0}
    };
    const PyCGLES2_Enum *e;
    for (e = enums; e->name != NULL; ++e)
        if (PyModule_AddIntConstant(m, e->name, e->value) != 0)
            return 0;
    return 1;
}


#endif /* GL_EXT_geometry_shader */
#endif /* _PYCGLES2_GL_EXT_GEOMETRY_SHADER_H_ */
