#ifndef _PYCGLES2_GL_OES_TEXTURE_COMPRESSION_ASTC_H_
#define _PYCGLES2_GL_OES_TEXTURE_COMPRESSION_ASTC_H_
#ifdef GL_OES_texture_compression_astc
#include <Python.h>
#include <pycgles2.h>
#include "gl.h"
#include "util.h"
#include "ctxstruct.h"


static int
PyCGLES2_GL_OES_texture_compression_astc(PyObject *m)
{
    static const PyCGLES2_Enum enums[] = {
        {"GL_COMPRESSED_RGBA_ASTC_3x3x3_OES", GL_COMPRESSED_RGBA_ASTC_3x3x3_OES},
        {"GL_COMPRESSED_RGBA_ASTC_4x3x3_OES", GL_COMPRESSED_RGBA_ASTC_4x3x3_OES},
        {"GL_COMPRESSED_RGBA_ASTC_4x4x3_OES", GL_COMPRESSED_RGBA_ASTC_4x4x3_OES},
        {"GL_COMPRESSED_RGBA_ASTC_4x4x4_OES", GL_COMPRESSED_RGBA_ASTC_4x4x4_OES},
        {"GL_COMPRESSED_RGBA_ASTC_5x4x4_OES", GL_COMPRESSED_RGBA_ASTC_5x4x4_OES},
        {"GL_COMPRESSED_RGBA_ASTC_5x5x4_OES", GL_COMPRESSED_RGBA_ASTC_5x5x4_OES},
        {"GL_COMPRESSED_RGBA_ASTC_5x5x5_OES", GL_COMPRESSED_RGBA_ASTC_5x5x5_OES},
        {"GL_COMPRESSED_RGBA_ASTC_6x5x5_OES", GL_COMPRESSED_RGBA_ASTC_6x5x5_OES},
        {"GL_COMPRESSED_RGBA_ASTC_6x6x5_OES", GL_COMPRESSED_RGBA_ASTC_6x6x5_OES},
        {"GL_COMPRESSED_RGBA_ASTC_6x6x6_OES", GL_COMPRESSED_RGBA_ASTC_6x6x6_OES},
        {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_3x3x3_OES", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_3x3x3_OES},
        {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x3x3_OES", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x3x3_OES},
        {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x3_OES", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x3_OES},
        {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x4_OES", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4x4_OES},
        {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4x4_OES", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4x4_OES},
        {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x4_OES", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x4_OES},
        {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x5_OES", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5x5_OES},
        {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5x5_OES", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5x5_OES},
        {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x5_OES", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x5_OES},
        {"GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x6_OES", GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6x6_OES},
        {NULL, 0}
    };
    const PyCGLES2_Enum *e;
    for (e = enums; e->name != NULL; ++e)
        if (PyModule_AddIntConstant(m, e->name, e->value) != 0)
            return 0;
    return 1;
}


#endif /* GL_OES_texture_compression_astc */
#endif /* _PYCGLES2_GL_OES_TEXTURE_COMPRESSION_ASTC_H_ */
